name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  hive_flutter: ^1.1.0
  hive: 2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 16 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
